version: "3.8"

services:
  apim:
    image: wso2/wso2am:latest
    container_name: wso2-apim
    ports:
    - "9443:9443"
    - "8243:8243"
    - "8280:8280"
    volumes:
      - ./data/db:/home/wso2carbon/wso2am-4.1.0/repository/database
    # user: root
    networks:
      - wso2
  backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
    image: hillushilbert/php-7.4-fpm:composer
    container_name: wso2-backend
    volumes:
      - ./backend:/var/www
    command: /bin/bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8080"
    ports:
    - "8081:8080"
    depends_on:
      - apim
    networks:
      - wso2
networks:
  wso2:
      driver: bridge
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/var/www/app
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mysql
  #     # - redis
  #   environment:
  #     - APP_URL=http://127.0.0.1:8080
  #     - APP_DEBUG=true
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_DATABASE=carrera-seguros
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=password

  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=carrera-seguros

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8090:80"
  #   links:
  #     - mysql
  #   environment:
  #     - PMA_HOST=mysql

  # redis:
  #   image: bitnami/redis:5.0.8-debian-10-r39
  #   volumes:
  #     - redis-data:/bitnami/redis/data
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

  # # Laravel Queues
  # queue:
  #   image: ambientum/php:7.3
  #   command: php artisan queue:listen
  #   volumes:
  #     - .:/var/www/app
  #   links:
  #     - mysql
  #     - redis

# volumes:
#   mysql-data:
#   # redis-data:
